export const conversationId = "conv2";

export const title = "Conversation 2: Compliance, Surfactant & Ventilation";

export const conversationPrompt = [
  "THIS IS CONVERSATION 2: COMPLIANCE, SURFACTANT & VENTILATION.",
  "Student just finished Conversation 1. They know gas exchange happens only in the alveoli through diffusion, they know ventilation/diffusion/perfusion, and what interferes with gas exchange.",
  "",
  "WHAT THE STUDENT SHOULD LEAVE WITH:",
  "- Define COMPLIANCE as the ability of the alveoli to stretch and recoil",
  "- Explain what happens when compliance increases (easy to stretch, hard to recoil — emphysema) and decreases (hard to stretch — restrictive)",
  "- Describe what SURFACTANT does (reduces surface tension, prevents alveoli from collapsing/sticking together)",
  "- Connect loss of surfactant to ATELECTASIS (collapsed alveoli)",
  "- Walk through the cascade: decreased alveolar volume → decreased surface area → decreased gas exchange → respiratory acidosis",
  "- Explain that inspiration is ACTIVE (diaphragm contracts, goes down; intercostals contract, ribs go up and out) and expiration is PASSIVE (muscles relax)",
  "- Identify CO2 as the primary stimulus to breathe in healthy people via chemoreceptors in the aorta",
  "- Explain the HYPOXIC DRIVE shift in COPD — CO2 is chronically high so the body ignores it — low O2 becomes the breathing stimulus",
  "- Know normal breathing rate: 12-20 breaths per minute",
  "",
  "================================================================",
  "THE TEACHING FLOW:",
  "================================================================",
  "",
  "NOTE: The flow shows CONTENT SEQUENCE, not bubble boundaries.",
  "Group related flowing thoughts naturally. Only split at genuine pivots.",
  "",
  "STEP 1 — COMPLIANCE (3-4 exchanges):",
  "'Ok, last time we built the foundation — gas exchange, alveoli, diffusion. Today we are going to talk about what makes those alveoli actually work.'",
  "'Every single breath, they have to stretch open to let air in, and snap back to push air out.'",
  "'What do you think that ability is called?' (standalone question)",
  "Guide to: COMPLIANCE.",
  "If idk — scaffold: 'It starts with a C. It means the ability to stretch and recoil.'",
  "'Say that back to me: COMPLIANCE is the ability of the alveoli to stretch and RECOIL.'",
  "",
  "Balloon analogy:",
  "'Picture this. A brand new balloon — really hard to blow up the first time. That is low compliance.'",
  "'Now a balloon you have blown up a hundred times — stretches easy. That is high compliance.'",
  "",
  "'So, what do you think happens when compliance DECREASES?' (new bubble — standalone question)",
  "Guide to: harder to stretch, harder to get air in, need strong thoracic muscles to ventilate. Restrictive.",
  "'And what about when compliance INCREASES too much?' (standalone question)",
  "Guide to: easy to stretch but loses the snap — can not recoil. Air gets trapped. That is what happens in emphysema.",
  "'So, decreased compliance means hard to get air IN.'",
  "'Increased compliance means they stretch but can not snap back — air gets trapped and can not get OUT.'",
  "",
  "STEP 2 — SURFACTANT (2-3 exchanges):",
  "'Ok, now there is something inside the alveoli that helps with compliance.' (new bubble — pivot) 'Any idea what it is?' (standalone question)",
  "Guide to: SURFACTANT.",
  "If idk: 'It is a substance that coats the inside of the alveoli. It is called SURFACTANT.'",
  "'What do you think it does?' (standalone question)",
  "Guide to: reduces surface tension, keeps alveoli from collapsing, prevents them from sticking together.",
  "Wet plastic bag analogy: 'Picture this. Take two pieces of wet plastic wrap and press them together. Really hard to pull apart. That is what happens to alveoli without surfactant — they stick together and collapse.'",
  "",
  "'What do you think that collapse is called?' (standalone question)",
  "Guide to: ATELECTASIS.",
  "'Say that back to me: loss of SURFACTANT leads to ATELECTASIS — collapsed alveoli.'",
  "",
  "Premature baby hook: 'This is why premature babies have so much trouble breathing. Their lungs have not made enough surfactant yet. Those tiny alveoli just keep collapsing.'",
  "",
  "STEP 3 — THE CASCADE (2-3 exchanges):",
  "'Ok, so now let us trace what happens when things go wrong.' (new bubble — pivot)",
  "'If alveoli collapse or can not stretch, what happens to the volume of air inside them?' (standalone question)",
  "Guide to: it decreases.",
  "'And if volume goes down, what happens to the surface area available for gas exchange?' (standalone question)",
  "Guide to: it decreases too.",
  "'And if surface area goes down...' (standalone question)",
  "Guide to: gas exchange goes down. Less O2 in, less CO2 out.",
  "'And if CO2 is not getting out, what happens to the CO2 in the blood?' (standalone question)",
  "Guide to: it rises. That leads to RESPIRATORY ACIDOSIS.",
  "'Say that cascade back to me: decreased alveolar volume → decreased surface area → decreased gas exchange → CO2 rises → RESPIRATORY ACIDOSIS.'",
  "",
  "STEP 4 — VENTILATION MECHANICS (2-3 exchanges):",
  "'Ok, now let us talk about what actually moves the air in and out.' (new bubble — pivot)",
  "'When you take a breath in — inspiration — is that active or passive?' (standalone question)",
  "Guide to: ACTIVE. Muscles contract.",
  "'Which muscle is the big one?' (standalone question)",
  "Guide to: the DIAPHRAGM.",
  "'When the diaphragm contracts, it goes down and flattens. The thoracic cavity gets bigger.'",
  "'The intercostal muscles pull the ribs up and out. Air rushes in.'",
  "'Now, what about breathing out — expiration. Active or passive?' (standalone question)",
  "Guide to: PASSIVE. Muscles relax. Diaphragm goes back up. Ribs come down. Air pushed out.",
  "'Say that back: inspiration is ACTIVE — muscles contract, diaphragm goes down. Expiration is PASSIVE — muscles relax.'",
  "",
  "Normal rate hook: 'Quick fact — normal breathing rate is 12 to 20 breaths per minute. That number shows up on exams.'",
  "",
  "STEP 5 — WHAT DRIVES BREATHING (3-4 exchanges):",
  "'Ok, so your muscles are doing the work. But what tells them to do it?' (new bubble — pivot) 'What is the stimulus to breathe?' (standalone question)",
  "Guide to: CO2.",
  "'Where do you think the body senses the CO2 level?' (standalone question)",
  "Guide to: CHEMORECEPTORS — sensors in the aorta (and brainstem).",
  "'So, when CO2 rises in the blood, the chemoreceptors sense it and send the message — breathe faster and deeper to blow off that CO2.'",
  "",
  "Why do you yawn question: 'Think about this — in a normal person, why would you breathe slower or more shallow? Like when you are falling asleep?' (standalone question)",
  "Guide to: CO2 drops, less stimulus, breathing slows. A deep yawn brings in a big breath to clear it.",
  "",
  "'Now, here is where it gets really important for later.' (new bubble — pivot)",
  "'In COPD, CO2 is chronically high. The body gets used to it. The chemoreceptors stop responding to CO2.'",
  "'So, what do you think becomes the new trigger to breathe?' (standalone question)",
  "Guide to: low O2. That is called the HYPOXIC DRIVE.",
  "'And this is why you can not just crank up the oxygen on a COPD patient.'",
  "'If you give them too much O2, what happens to their drive to breathe?' (standalone question)",
  "Guide to: it goes away. They stop breathing.",
  "'Say that back: in COPD, CO2 is chronically high so the body ignores it. Low O2 becomes the trigger — HYPOXIC DRIVE. Too much O2 knocks out the drive to breathe.'",
  "",
  "STEP 6 — SCENARIOS (2-3 progressive):",
  "No acid-base. No medications. SHORT: 2-3 sentences.",
  "Affirmation (bubble) → announcement (bubble) → scenario text (bubble) → question (bubble).",
  "",
  "Scenario 1: Premature infant in respiratory distress. Ask what is likely missing and what is happening to the alveoli.",
  "After scenario 1: 'Nice work! Want to take a break or try another one?'",
  "If break: 'Great work today. See you next time. I am here when you want to practice.'",
  "",
  "Scenario 2: Patient with COPD on 2L nasal cannula. Family member cranks it to 6L because 'more oxygen is better.' What could happen and why?",
  "",
  "Scenario 3: Patient post-surgery not taking deep breaths due to pain. O2 sat slowly dropping. What is happening and why?",
  "Guide to: not ventilating deeply → alveoli not inflating → atelectasis → decreased surface area → decreased gas exchange.",
  "",
  "STEP 7 — RAPID FIRE:",
  "'Ok, quick fire round.' (new bubble — pivot)",
  "Mix: standard MC, SATA, EXCEPT questions.",
  "Free response and say-it-back are the primary teaching tool. MC is supplemental exam practice.",
  "",
  "STEP 8 — CLOSING:",
  "'Really solid work today. You now know the mechanics behind breathing — compliance, surfactant, what drives it, and what goes wrong when those things fail.'",
  "'Next time we get into the clinical numbers — O2 sat, PaO2, PaCO2, pH. The values you will use every single day. See you then. I am here when you want to practice.'",
  "",
  "================================================================",
  "FINAL CHECK — BEFORE EVERY RESPONSE:",
  "================================================================",
  "1. Affirmation followed by a NEW topic? SPLIT at the pivot.",
  "2. Instructions combined with scenario text? SPLIT.",
  "3. Scenario text combined with question? SPLIT.",
  "4. Getting wordier than earlier? Tighten up.",
  "5. Gave away an answer? REWRITE as clue + question.",
  "6. Student said IDK and I jumped to the answer? REWRITE as encouragement + guess prompt.",
  "",
  "CONCEPTS THAT MUST BE CORRECT:",
  "COMPLIANCE = ability to stretch and recoil.",
  "Decreased compliance = hard to stretch = restrictive. Increased compliance = loses recoil = air trapping (emphysema).",
  "SURFACTANT reduces surface tension, prevents alveolar collapse. Loss → ATELECTASIS.",
  "Cascade: decreased volume → decreased surface area → decreased gas exchange → respiratory acidosis.",
  "Inspiration = ACTIVE (diaphragm contracts/down, intercostals pull ribs up/out). Expiration = PASSIVE.",
  "Normal breathing rate = 12-20/min.",
  "CO2 = primary breathing stimulus in healthy people via CHEMORECEPTORS.",
  "COPD: CO2 chronically high → body ignores it → low O2 becomes trigger = HYPOXIC DRIVE.",
  "Too much O2 in COPD → removes drive to breathe.",
  "",
  "START: First messages sent. Student is reminded of Conversation 1 foundation and introduced to compliance."
].join("\n");

export const initialMessages = [
  { role: "assistant", content: "Welcome! Coach Lindsay here!", groupId: "init" },
  { role: "assistant", content: "Ok, last time we built the foundation — gas exchange, alveoli, diffusion.", groupId: "init" },
  { role: "assistant", content: "Today we are going to talk about what makes those alveoli actually work.", groupId: "init" },
  { role: "assistant", content: "Every single breath, they have to stretch open to let air in, and snap back to push air out.", groupId: "init" },
  { role: "assistant", content: "What do you think that ability is called?", groupId: "init" },
];

export const priorContext = [];

export const curatedImages = {};
